# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ASUS\cal.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.setWindowModality(QtCore.Qt.WindowModal)
        Calculator.resize(461, 672)
        Calculator.setFixedSize(461, 672)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        Calculator.setFont(font)
        Calculator.setMouseTracking(True)
        self.pushButton_MC = QtWidgets.QPushButton(Calculator)
        self.pushButton_MC.setGeometry(QtCore.QRect(0, 200, 101, 51))
        self.pushButton_MC.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_MC.setFont(font)
        self.pushButton_MC.setObjectName("pushButton_MC")
        self.pushButton_MR = QtWidgets.QPushButton(Calculator)
        self.pushButton_MR.setGeometry(QtCore.QRect(100, 200, 91, 51))
        self.pushButton_MR.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_MR.setFont(font)
        self.pushButton_MR.setObjectName("pushButton_MR")
        self.pushButton_M_Substract = QtWidgets.QPushButton(Calculator)
        self.pushButton_M_Substract.setGeometry(QtCore.QRect(280, 200, 91, 51))
        self.pushButton_M_Substract.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_M_Substract.setFont(font)
        self.pushButton_M_Substract.setObjectName("pushButton_M_Substract")
        self.pushButton_M_Plus = QtWidgets.QPushButton(Calculator)
        self.pushButton_M_Plus.setGeometry(QtCore.QRect(190, 200, 91, 51))
        self.pushButton_M_Plus.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_M_Plus.setFont(font)
        self.pushButton_M_Plus.setObjectName("pushButton_M_Plus")
        self.pushButton_MS = QtWidgets.QPushButton(Calculator)
        self.pushButton_MS.setGeometry(QtCore.QRect(370, 200, 91, 51))
        self.pushButton_MS.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_MS.setFont(font)
        self.pushButton_MS.setObjectName("pushButton_MS")
        self.pushButton_CE = QtWidgets.QPushButton(Calculator)
        self.pushButton_CE.setGeometry(QtCore.QRect(0, 370, 111, 61))
        self.pushButton_CE.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_CE.setFont(font)
        self.pushButton_CE.setObjectName("pushButton_CE")
        self.pushButton_C = QtWidgets.QPushButton(Calculator)
        self.pushButton_C.setGeometry(QtCore.QRect(110, 370, 111, 61))
        self.pushButton_C.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_C.setFont(font)
        self.pushButton_C.setObjectName("pushButton_C")
        self.pushButton_Backspace = QtWidgets.QPushButton(Calculator)
        self.pushButton_Backspace.setGeometry(QtCore.QRect(220, 370, 111, 61))
        self.pushButton_Backspace.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_Backspace.setFont(font)
        self.pushButton_Backspace.setObjectName("pushButton_Backspace")
        self.pushButton_Divide = QtWidgets.QPushButton(Calculator)
        self.pushButton_Divide.setGeometry(QtCore.QRect(330, 370, 131, 61))
        self.pushButton_Divide.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_Divide.setFont(font)
        self.pushButton_Divide.setObjectName("pushButton_Divide")
        self.pushButton_7 = QtWidgets.QPushButton(Calculator)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 430, 111, 61))
        self.pushButton_7.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_5 = QtWidgets.QPushButton(Calculator)
        self.pushButton_5.setGeometry(QtCore.QRect(110, 490, 111, 61))
        self.pushButton_5.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(Calculator)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 490, 111, 61))
        self.pushButton_4.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_Opposite = QtWidgets.QPushButton(Calculator)
        self.pushButton_Opposite.setGeometry(QtCore.QRect(0, 610, 111, 61))
        self.pushButton_Opposite.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_Opposite.setFont(font)
        self.pushButton_Opposite.setObjectName("pushButton_Opposite")
        self.pushButton_1 = QtWidgets.QPushButton(Calculator)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 550, 111, 61))
        self.pushButton_1.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_8 = QtWidgets.QPushButton(Calculator)
        self.pushButton_8.setGeometry(QtCore.QRect(110, 430, 111, 61))
        self.pushButton_8.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_2 = QtWidgets.QPushButton(Calculator)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 550, 111, 61))
        self.pushButton_2.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_0 = QtWidgets.QPushButton(Calculator)
        self.pushButton_0.setGeometry(QtCore.QRect(110, 610, 111, 61))
        self.pushButton_0.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_9 = QtWidgets.QPushButton(Calculator)
        self.pushButton_9.setGeometry(QtCore.QRect(220, 430, 111, 61))
        self.pushButton_9.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_6 = QtWidgets.QPushButton(Calculator)
        self.pushButton_6.setGeometry(QtCore.QRect(220, 490, 111, 61))
        self.pushButton_6.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_3 = QtWidgets.QPushButton(Calculator)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 550, 111, 61))
        self.pushButton_3.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_Point = QtWidgets.QPushButton(Calculator)
        self.pushButton_Point.setGeometry(QtCore.QRect(220, 610, 111, 61))
        self.pushButton_Point.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_Point.setFont(font)
        self.pushButton_Point.setObjectName("pushButton_Point")
        self.pushButton_Multiply = QtWidgets.QPushButton(Calculator)
        self.pushButton_Multiply.setGeometry(QtCore.QRect(330, 430, 131, 61))
        self.pushButton_Multiply.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_Multiply.setFont(font)
        self.pushButton_Multiply.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton_Multiply.setObjectName("pushButton_Multiply")
        self.pushButton_Substract = QtWidgets.QPushButton(Calculator)
        self.pushButton_Substract.setGeometry(QtCore.QRect(330, 490, 131, 61))
        self.pushButton_Substract.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_Substract.setFont(font)
        self.pushButton_Substract.setObjectName("pushButton_Substract")
        self.pushButton_Plus = QtWidgets.QPushButton(Calculator)
        self.pushButton_Plus.setGeometry(QtCore.QRect(330, 550, 131, 61))
        self.pushButton_Plus.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_Plus.setFont(font)
        self.pushButton_Plus.setObjectName("pushButton_Plus")
        self.pushButton_Equal = QtWidgets.QPushButton(Calculator)
        self.pushButton_Equal.setGeometry(QtCore.QRect(330, 610, 131, 61))
        self.pushButton_Equal.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_Equal.setFont(font)
        self.pushButton_Equal.setObjectName("pushButton_Equal")
        self.label = QtWidgets.QLabel(Calculator)
        self.label.setGeometry(QtCore.QRect(0, 0, 461, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Caslon Pro")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_Square = QtWidgets.QPushButton(Calculator)
        self.pushButton_Square.setGeometry(QtCore.QRect(220, 310, 111, 61))
        self.pushButton_Square.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_Square.setFont(font)
        self.pushButton_Square.setObjectName("pushButton_Square")
        self.pushButton_Evolution = QtWidgets.QPushButton(Calculator)
        self.pushButton_Evolution.setGeometry(QtCore.QRect(110, 310, 111, 61))
        self.pushButton_Evolution.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_Evolution.setFont(font)
        self.pushButton_Evolution.setObjectName("pushButton_Evolution")
        self.pushButton_Module = QtWidgets.QPushButton(Calculator)
        self.pushButton_Module.setGeometry(QtCore.QRect(0, 310, 111, 61))
        self.pushButton_Module.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_Module.setFont(font)
        self.pushButton_Module.setObjectName("pushButton_Module")
        self.pushButton_Reciprocal = QtWidgets.QPushButton(Calculator)
        self.pushButton_Reciprocal.setGeometry(QtCore.QRect(330, 310, 131, 61))
        self.pushButton_Reciprocal.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_Reciprocal.setFont(font)
        self.pushButton_Reciprocal.setObjectName("pushButton_Reciprocal")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Calculator)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 40, 461, 161))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(461, 161))
        font = QtGui.QFont()
        font.setFamily("Adobe Garamond Pro")
        font.setPointSize(25)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.plainTextEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.plainTextEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.plainTextEdit.setAutoFillBackground(False)
        self.plainTextEdit.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.plainTextEdit.setTabChangesFocus(False)
        self.plainTextEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setCenterOnScroll(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_Pi = QtWidgets.QPushButton(Calculator)
        self.pushButton_Pi.setGeometry(QtCore.QRect(0, 250, 111, 61))
        self.pushButton_Pi.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_Pi.setFont(font)
        self.pushButton_Pi.setObjectName("pushButton_Pi")
        self.pushButton_Ln = QtWidgets.QPushButton(Calculator)
        self.pushButton_Ln.setGeometry(QtCore.QRect(110, 250, 111, 61))
        self.pushButton_Ln.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_Ln.setFont(font)
        self.pushButton_Ln.setObjectName("pushButton_Ln")
        self.pushButton_Sin = QtWidgets.QPushButton(Calculator)
        self.pushButton_Sin.setGeometry(QtCore.QRect(220, 250, 111, 61))
        self.pushButton_Sin.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_Sin.setFont(font)
        self.pushButton_Sin.setObjectName("pushButton_Sin")
        self.pushButton_Cos = QtWidgets.QPushButton(Calculator)
        self.pushButton_Cos.setGeometry(QtCore.QRect(330, 250, 131, 61))
        self.pushButton_Cos.setMaximumSize(QtCore.QSize(131, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.pushButton_Cos.setFont(font)
        self.pushButton_Cos.setObjectName("pushButton_Cos")

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Form"))
        self.pushButton_MC.setText(_translate("Calculator", "MC"))
        self.pushButton_MR.setText(_translate("Calculator", "MR"))
        self.pushButton_M_Substract.setText(_translate("Calculator", "M-"))
        self.pushButton_M_Plus.setText(_translate("Calculator", "M+"))
        self.pushButton_MS.setText(_translate("Calculator", "MS"))
        self.pushButton_CE.setText(_translate("Calculator", "CE"))
        self.pushButton_C.setText(_translate("Calculator", "C"))
        self.pushButton_Backspace.setText(_translate("Calculator", "←"))
        self.pushButton_Divide.setText(_translate("Calculator", "÷"))
        self.pushButton_7.setText(_translate("Calculator", "7"))
        self.pushButton_5.setText(_translate("Calculator", "5"))
        self.pushButton_4.setText(_translate("Calculator", "4"))
        self.pushButton_Opposite.setText(_translate("Calculator", "±"))
        self.pushButton_1.setText(_translate("Calculator", "1"))
        self.pushButton_8.setText(_translate("Calculator", "8"))
        self.pushButton_2.setText(_translate("Calculator", "2"))
        self.pushButton_0.setText(_translate("Calculator", "0"))
        self.pushButton_9.setText(_translate("Calculator", "9"))
        self.pushButton_6.setText(_translate("Calculator", "6"))
        self.pushButton_3.setText(_translate("Calculator", "3"))
        self.pushButton_Point.setText(_translate("Calculator", "."))
        self.pushButton_Multiply.setText(_translate("Calculator", "×"))
        self.pushButton_Substract.setText(_translate("Calculator", "-"))
        self.pushButton_Plus.setText(_translate("Calculator", "+"))
        self.pushButton_Equal.setText(_translate("Calculator", "="))
        self.label.setText(_translate("Calculator", "Simple Calculator"))
        self.pushButton_Square.setText(_translate("Calculator", "x²"))
        self.pushButton_Evolution.setText(_translate("Calculator", "√"))
        self.pushButton_Module.setText(_translate("Calculator", "%"))
        self.pushButton_Reciprocal.setText(_translate("Calculator", "¹/x"))
        self.pushButton_Pi.setText(_translate("Calculator", " π"))
        self.pushButton_Ln.setText(_translate("Calculator", "ln"))
        self.pushButton_Sin.setText(_translate("Calculator", "sin"))
        self.pushButton_Cos.setText(_translate("Calculator", "cos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QWidget()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec_())

